name: Deploy static content to Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Pages
      uses: actions/configure-pages@v4

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './docs'  # Path to your static files

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}